### ISSUE TITLE
Can't get "Retain control while Linked" to work ToX1

### ISSUE THREAD

**Issue by Noctuali** [ucuckic/tales_patches#1]
Hello, I'm unable to get the "Retain control while Linked" feature to work with Tales of Xillia 1 and I'm wondering if you'd be willing to offer any assistance.

I've tried using RPCS3 version 0.0.25-14515-02f3583 Alpha and the newest available version. The patch / feature shows up and I'm able to check it off in "Manage game patches" but the log file doesn't show it loading and it doesn't work in-game. Is there something needed besides RPCS3 and the tox_1_patch.yml file?

My game serial is NPUB31136 and the PPU hash in the rpcs3 log when launching the game matches the hash listed in the patch (PPU-a7f26bbbcb13fd5f554d0612f490861feec78e8f).

I'm not sure what else to check. The 60fps patch works fine, I just can't get this one to work.

Thank you for any help you can offer!

**Comment by ucuckic** [comment]
even though patches with filenames other than imported_patch.yml will be loaded from the patches folder to be selected in the list, they will not actually be loaded ingame (rpcs3 has tons of stupid shit like this)
you must add the patch to your imported_patch.yml file in the patches folder

**Comment by Noctuali** [comment]
That fixed it! Thank you. I'm glad it was something simple and I'm sorry that I missed that. I've only used the built-in patches so far and haven't had to create the imported_patch.yml file previously.

Thank you so much again. I'm starting a 4-player playthrough with friends and this will help!
